---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db
  namespace: wordpress
type: Opaque
stringData:
  database: wordpress
  username: wordpress
  password: "StrongPassword_123!"
  root-password: "RootPassword_456!"
