---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: wordpress
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress
  namespace: wordpress
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
  namespace: wordpress
automountServiceAccountToken: false

